# Generated by Django 5.2 on 2025-04-23 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_goal_usergoal'),
        ('core', '0004_profile'),
    ]

    operations = [
    ]
